const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let cfg=null,currentPreview="index.html",selected=null,previewHTML="";
async function api(path,opt={}){const r=await fetch(path,{credentials:"same-origin",...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),2400)}
function msg(role,text){const e=document.createElement("div");e.className="msg "+role;e.innerHTML='<div class="avatar">'+(role==="user"?"You":"F")+'</div><div class="bubble">'+esc(text)+'</div>';$("#messages").append(e);$("#messages").scrollTop=$("#messages").scrollHeight}
function renderProviders(){const p=cfg.providers;const options=p.map(x=>'<option value="'+esc(x.name)+'">'+esc(x.name)+'</option>').join("");$("#providerSelect").innerHTML=options;$("#settingsProvider").innerHTML=options;$("#providerSelect").value=cfg.default_provider;$("#settingsProvider").value=cfg.default_provider;models()}
function models(){const p=cfg.providers.find(x=>x.name===$("#providerSelect").value)||cfg.providers[0];$("#modelSelect").innerHTML='<option>'+esc(p.default_model)+'</option>';const sp=cfg.providers.find(x=>x.name===$("#settingsProvider").value)||p;$("#settingsModel").value=sp.default_model}
function keys(){$("#keyRows").innerHTML=cfg.providers.map(p=>'<div class="key-row"><span>'+esc(p.name)+'</span><span class="configured">'+(p.configured?"Configured":"Not configured")+"</span></div>").join("")}
async function loadConfig(){cfg=await api("/v1/config");renderProviders();keys();$("#workspacePath").textContent=cfg.workspace;$("#statusText").textContent="Ready"}
function setProgress(percent,label){$("#generationProgress").hidden=false;$("#progressFill").style.width=Math.max(0,Math.min(100,percent))+"%";$("#progressPercent").textContent=Math.round(percent)+"%";$("#progressLabel").textContent=label}
function finishProgress(){setProgress(100,"Complete");setTimeout(()=>$("#generationProgress").hidden=true,800)}
async function send(){const b=$("#prompt"),p=b.value.trim();if(!p)return;b.value="";b.style.height="auto";msg("user",p);$("#sendBtn").disabled=true;let timer=null;try{setProgress(8,"Connecting to model");let progress=8;timer=setInterval(()=>{progress=Math.min(progress+Math.random()*4.5,88);const label=progress<25?"Preparing request":progress<55?"Generating implementation":progress<75?"Assembling response":"Validating complete response";setProgress(progress,label)},450);const d=await api("/v1/chat",{method:"POST",body:JSON.stringify({prompt:p,provider:$("#providerSelect").value,model:$("#modelSelect").value,apply:true,billing_mode:$("#billingMode").value})});clearInterval(timer);setProgress(92,"Finalizing response");msg("assistant",d.content+(d.written_files?.length?"\n\nChanged:\n"+d.written_files.join("\n"):""));finishProgress();if(d.written_files?.some(x=>/\.(html?|css|js)$/i.test(x)))loadBuilder(currentPreview)}catch(e){if(timer)clearInterval(timer);setProgress(100,"Failed");msg("assistant","Request failed: "+e.message);setTimeout(()=>$("#generationProgress").hidden=true,1200)}finally{$("#sendBtn").disabled=false;b.focus()}}
async function files(){const d=await api("/v1/files");return d.files}
function isSiteFile(f){return /\.(html?|css|js|mjs|json|svg|png|jpe?g|webp|gif|ico|woff2?|ttf|otf)$/i.test(f)}
async function loadBuilder(preferred){const all=await files();const site=all.filter(isSiteFile);$("#fileCount").textContent=site.length;$("#builderFileList").innerHTML=site.map(f=>'<button class="file-row '+(f===currentPreview?"selected":"")+'" data-file="'+encodeURIComponent(f)+'">'+esc(f)+"</button>").join("");const htmls=site.filter(f=>/\.html?$/i.test(f));const target=htmls.includes(preferred)?preferred:(htmls[0]||"");$("#previewFile").innerHTML=htmls.length?htmls.map(f=>'<option value="'+esc(f)+'">'+esc(f)+"</option>").join(""):'<option value="">No HTML page</option>';if(target){$("#previewFile").value=target;currentPreview=target;openSite(target)}$$(".builder-files .file-row").forEach(e=>e.onclick=()=>{const f=decodeURIComponent(e.dataset.file);if(/\.html?$/i.test(f))openSite(f);else editRawFile(f)})}
async function runRuntimePreview(){try{$("#runRuntimePreview").disabled=true;$("#previewStatus").textContent="Starting local runtime…";const runtime=$("#runtimeSelect").value;const d=await api("/v1/preview/runtime?runtime="+encodeURIComponent(runtime),{method:"POST"});$("#sitePreview").sandbox="allow-scripts allow-forms";$("#sitePreview").src=d.url+"?fuzecli="+Date.now();$("#previewStatus").textContent="Live "+d.kind+" runtime · "+d.url;toast(d.kind.toUpperCase()+" preview running")}catch(e){$("#previewStatus").textContent="Runtime preview unavailable";toast(e.message)}finally{$("#runRuntimePreview").disabled=false}}
function openSite(file=currentPreview){if(!file)return;currentPreview=file;selected=null;$("#sitePreview").sandbox="allow-scripts allow-forms";$("#inspectorForm").hidden=true;$("#inspectorEmpty").hidden=false;$("#selectedPath").textContent="Nothing selected";$("#sitePreview").src="/preview/"+encodeURI(file)+"?t="+Date.now();$$(".builder-files .file-row").forEach(e=>e.classList.toggle("selected",decodeURIComponent(e.dataset.file)===file))}
async function editRawFile(file){try{const d=await api("/v1/file?path="+encodeURIComponent(file));$("#selectedPath").textContent=file;$("#inspectorEmpty").hidden=false;$("#inspectorForm").hidden=true;toast(file+" opened in Files")}catch(e){toast(e.message)}}
function postEditor(type,payload={}){$("#sitePreview").contentWindow?.postMessage({source:"fuzecli-editor",type,...payload},"*")}
function applyInspector(){if(!selected)return;const styles={color:$("#editColor").value.trim(),backgroundColor:$("#editBackground").value.trim(),fontSize:$("#editFontSize").value.trim(),padding:$("#editPadding").value.trim(),borderRadius:$("#editRadius").value.trim()};Object.keys(styles).forEach(k=>{if(!styles[k])delete styles[k]});postEditor("text",{value:$("#editText").value});postEditor("style",{styles});toast("Change applied live")}
async function savePreview(){if(!previewHTML){postEditor("request-html");return}await api("/v1/file",{method:"POST",body:JSON.stringify({path:currentPreview,content:previewHTML})});toast("Saved "+currentPreview);await loadBuilder(currentPreview)}
function builderMessage(e){const d=e.data;if(!d||d.source!=="fuzecli-preview")return;if(d.type==="ready"){$("#previewStatus").textContent="Live · click an element to inspect"}if(d.type==="select"){selected=d;$("#previewStatus").textContent="Selected "+d.tag;$("#selectedPath").textContent=d.path;$("#inspectorEmpty").hidden=true;$("#inspectorForm").hidden=false;$("#selectedTag").textContent=d.tag.toUpperCase();$("#editText").value=d.text||"";$("#editColor").value=d.color||"";$("#editBackground").value=d.background||"";$("#editFontSize").value=d.fontSize||"";$("#editPadding").value=d.padding||"";$("#editRadius").value=d.radius||""}if(d.type==="changed"){previewHTML=d.html;$("#previewStatus").textContent="Unsaved changes"}}
async function workspace(){const d=await api("/v1/files");$("#workspaceFileCount").textContent=d.files.length;$("#fileList").innerHTML=d.files.map(f=>'<button class="file-row" data-f="'+encodeURIComponent(f)+'">'+esc(f)+"</button>").join("");$$(".file-panel .file-row").forEach(e=>e.onclick=async()=>{try{const d=await api("/v1/file?path="+e.dataset.f);$("#fileName").textContent=d.path;$("#fileContent").textContent=d.content}catch(x){toast(x.message)}})}
async function activity(){const d=await api("/v1/history");$("#activityList").innerHTML=d.messages.length?d.messages.map(m=>'<div class="activity-row"><div class="activity-role">'+esc(m.role)+"</div><div>"+esc(m.content)+"</div></div>").join(""):'<div class="activity-row">No activity yet.</div>'}
function view(v){$$(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===v));$$(".view").forEach(x=>x.classList.toggle("active",x.id==="view-"+v));$("#pageTitle").textContent=v==="builder"?"Live Builder":v[0].toUpperCase()+v.slice(1);if(v==="builder")loadBuilder(currentPreview);if(v==="workspace")workspace();if(v==="activity")activity()}
async function save(){try{await api("/v1/config",{method:"POST",body:JSON.stringify({provider:$("#settingsProvider").value,model:$("#settingsModel").value.trim()})});toast("Settings saved");await loadConfig()}catch(e){toast(e.message)}}
$$(".nav-item").forEach(b=>b.onclick=()=>view(b.dataset.view));
$$(".quick-actions button").forEach(b=>b.onclick=()=>{$("#prompt").value=b.dataset.prompt;$("#prompt").focus();$("#prompt").dispatchEvent(new Event("input"))});
$("#providerSelect").onchange=models;$("#refreshMemoryBtn").onclick=async()=>{try{await api("/v1/memory/refresh",{method:"POST"});toast("Conversation memory refreshed")}catch(e){toast(e.message)}};$("#settingsProvider").onchange=models;$("#sendBtn").onclick=send;$("#saveProvider").onclick=save;$("#refreshBtn").onclick=()=>loadConfig().then(()=>toast("Runtime refreshed"));$("#workspaceRefresh").onclick=workspace;$("#activityRefresh").onclick=activity;$("#previewFile").onchange=e=>openSite(e.target.value);$("#runRuntimePreview").onclick=runRuntimePreview;$("#openPreview").onclick=()=>window.open("/preview/"+encodeURI(currentPreview),"_blank","noopener");$("#savePreview").onclick=savePreview;$("#requestSavePreview").onclick=savePreview;$("#applyInspector").onclick=applyInspector;$("#deviceDesktop").onclick=()=>{$("#deviceFrame").className="device desktop"};$("#deviceMobile").onclick=()=>{$("#deviceFrame").className="device mobile"};window.addEventListener("message",builderMessage);
$("#prompt").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}};$("#prompt").oninput=e=>{e.target.style.height="auto";e.target.style.height=Math.min(e.target.scrollHeight,180)+"px"};
(async()=>{try{await loadConfig();await activity()}catch(e){$("#statusText").textContent="Offline";toast(e.message)}})();