package moonshot

import("context";"encoding/json";"fmt";"io";"net/http";"os";"strings";"time"
"github.com/Enoch7768/fuzecli/internal/provider"
"github.com/Enoch7768/fuzecli/internal/provider/transport")

const(defaultBaseURL="https://api.moonshot.cn/v1";apiKeyEnv="MOONSHOT_API_KEY";maxInputChars=22000;maxOutputTokens=3500;jsonOutputTokens=3000;minInterval=3*time.Second)
type Provider struct{apiKey,baseURL string;httpClient *http.Client}
func New(apiKey,baseURL string)*Provider{if strings.TrimSpace(apiKey)==""{apiKey=os.Getenv(apiKeyEnv)};if strings.TrimSpace(baseURL)==""{baseURL=defaultBaseURL};return &Provider{apiKey:strings.TrimSpace(apiKey),baseURL:strings.TrimRight(strings.TrimSpace(baseURL),"/"),httpClient:&http.Client{Timeout:120*time.Second}}}
func(p *Provider)Name()string{return "moonshot"}
func(p *Provider)headers()map[string]string{h:=map[string]string{};if p.apiKey!=""{h["Authorization"]="Bearer "+p.apiKey};return h}
func(p *Provider)request(ctx context.Context,b any)(transport.Result,error){if p.baseURL==""{return transport.Result{},fmt.Errorf("moonshot: base URL is not configured")};return transport.DoJSON(ctx,p.httpClient,http.MethodPost,p.baseURL+"/chat/completions",p.headers(),b)}
func providerError(n string,s int,h http.Header,b []byte)error{k:=provider.ErrorUnknown;switch s{case 401,403:k=provider.ErrorUnauthorized;case 404:k=provider.ErrorModelNotFound;case 408,429:k=provider.ErrorRateLimited;case 500,502,503,504:k=provider.ErrorProviderUnavailable;default:if s>=400{k=provider.ErrorBadRequest}};var d struct{Message string `json:"message"`};_ = json.Unmarshal(b,&d);m:=strings.TrimSpace(d.Message);if m==""{m=strings.TrimSpace(string(b))};if m==""{m=http.StatusText(s)};return &provider.ProviderError{Kind:k,Provider:n,StatusCode:s,Message:m,RetryAfter:transport.RetryAfter(h)}}
func(p *Provider)Send(ctx context.Context,msg []provider.Message,o provider.RequestOptions)(*provider.Response,error){model:=strings.TrimSpace(o.Model);if model==""||strings.EqualFold(model,"auto"){model="default"};b:=map[string]any{"model":model,"messages":msg,"temperature":o.Temperature,"max_tokens":o.MaxTokens};if o.JSONMode{b["response_format"]=map[string]any{"type":"json_schema","json_schema":map[string]any{"name":"fuzecli_response","strict":opts.JSONSchemaStrict,"schema":o.JSONSchema}}};r,e:=p.request(ctx,b);if e!=nil{return nil,&provider.ProviderError{Kind:provider.ErrorProviderUnavailable,Provider:p.Name(),Message:"request failed",Err:e}};if r.StatusCode<200||r.StatusCode>=300{return nil,providerError(p.Name(),r.StatusCode,r.Headers,r.Body)};var out struct{Model string `json:"model"`;Choices []struct{Message struct{Content string `json:"content"`} `json:"message"`} `json:"choices"`;Usage provider.Usage `json:"usage"`};if e=json.Unmarshal(r.Body,&out);e!=nil{return nil,fmt.Errorf("moonshot: invalid response: %w",e)};if len(out.Choices)==0{return nil,fmt.Errorf("moonshot: response contained no choices")};return &provider.Response{Content:out.Choices[0].Message.Content,Model:out.Model,ProviderName:p.Name(),Usage:out.Usage},nil}
func(p *Provider)Stream(ctx context.Context,msg []provider.Message,o provider.RequestOptions)(<-chan provider.StreamChunk,error){model:=strings.TrimSpace(o.Model);if model==""||strings.EqualFold(model,"auto"){model="default"};b:=map[string]any{"model":model,"messages":msg,"temperature":o.Temperature,"max_tokens":o.MaxTokens,"stream":true};if o.JSONMode{b["response_format"]=map[string]any{"type":"json_schema","json_schema":map[string]any{"name":"fuzecli_response","strict":opts.JSONSchemaStrict,"schema":o.JSONSchema}}};r,e:=transport.OpenSSE(ctx,p.httpClient,http.MethodPost,p.baseURL+"/chat/completions",p.headers(),b);if e!=nil{return nil,&provider.ProviderError{Kind:provider.ErrorProviderUnavailable,Provider:p.Name(),Message:"stream request failed",Err:e}};if r.StatusCode<200||r.StatusCode>=300{d,_:=io.ReadAll(r.Body);r.Body.Close();return nil,providerError(p.Name(),r.StatusCode,r.Header,d)};out:=make(chan provider.StreamChunk);go func(){defer close(out);e:=transport.ReadSSE(ctx,r,func(d string)error{if d=="[DONE]"{out<-provider.StreamChunk{Done:true};return nil};var c struct{Choices []struct{Delta struct{Content string `json:"content"`} `json:"delta"`} `json:"choices"`};if e:=json.Unmarshal([]byte(d),&c);e!=nil{return e};if len(c.Choices)>0&&c.Choices[0].Delta.Content!=""{out<-provider.StreamChunk{Delta:c.Choices[0].Delta.Content}};return nil});if e!=nil{out<-provider.StreamChunk{Error:e};return};out<-provider.StreamChunk{Done:true}}();return out,nil}
func(p *Provider)ListModels(ctx context.Context)([]string,error){if p.baseURL==""{return nil,fmt.Errorf("moonshot: base URL is not configured")};r,e:=transport.DoJSON(ctx,p.httpClient,http.MethodGet,p.baseURL+"/models",p.headers(),nil);if e!=nil{return nil,e};if r.StatusCode<200||r.StatusCode>=300{return nil,providerError(p.Name(),r.StatusCode,r.Headers,r.Body)};var out struct{Data []struct{ID string `json:"id"`} `json:"data"`};if e=json.Unmarshal(r.Body,&out);e!=nil{return nil,e};m:=make([]string,0,len(out.Data));for _,x:=range out.Data{if strings.TrimSpace(x.ID)!=""{m=append(m,x.ID)}};return m,nil}
